### ISSUE TITLE
Station Code

### ISSUE THREAD

**Issue by thanhnmit91** [yasuohasegawa/SwiftSuicaReaderSample#1]
Where do you get this file from? (StationCode.csv). Can you share with me? Thank you!
AreaCode,LineCode,StationCode,CompanyName,LineName,StationName,Note
0,0,0,JR東日本,上越新幹線,長岡,
0,0,0,ＪＲ東日本,上越新幹線,長岡,
....
...
...

**Comment by yasuohasegawa** [comment]
Hey! I've got that file from the following link.
I don't know that they have the latest one. Hope this helps you.
https://wp.utopiat.net/wp-content/uploads/2017/08/StationCode.csv

**Comment by thanhnmit91** [comment]
Thank you so much!
